version: "3.9"
   
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: AnotherVintage
    ports:
      - 27017:27017
    volumes:
      - database:\data\database
volumes:
  database:
    external: true